### ISSUE TITLE
 Cannot read properties of undefined (reading 'Solver')

### ISSUE THREAD

**Issue by KazutoKashima** [ScarletAI/Scarlet#17]
Error:
```js
dist\scarlet\RNN\RNN.core.js:45
    static Solver = new rnn_1.R.Solver();
                                ^

TypeError: Cannot read properties of undefined (reading 'Solver')
    at Function.<static_initializer> (C:\Users\Phoenix\Desktop\scarlet-api\v2-RNN_Remake\dist\scarlet\RNN\RNN.core.js:45:33)
    at Object.<anonymous> (C:\Users\Phoenix\Desktop\scarlet-api\v2-RNN_Remake\dist\scarlet\RNN\RNN.core.js:35:19)
    at Module._compile (node:internal/modules/cjs/loader:1097:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1149:10)
    at Module.load (node:internal/modules/cjs/loader:975:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:999:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (C:\Users\Phoenix\Desktop\scarlet-api\v2-RNN_Remake\dist\scarlet\Scarlet.js:6:20)
    at Module._compile (node:internal/modules/cjs/loader:1097:14)
```

Upcoming fix: Change from `function` to `class`

**Comment by KazutoKashima** [comment]
Solved in #18
